//! End-to-end test harness for `mls-rs-uniffi` with the RustCrypto
//! backend.
//!
//! This exercises the exact API surface that is exported to Swift,
//! Kotlin and WASM bindings:
//!
//! * `generate_signature_keypair` for every supported cipher suite
//!   (MLS suites 1, 2, 3, 5 and 7),
//! * `Client::new` (basic credentials) and `Client::new_with_x509`
//!   (X.509 credentials backed by the RustCrypto validator),
//! * group creation, key-package generation, `add_members`,
//!   `join_group`, `encrypt_application_message`,
//!   `process_incoming_message`, `commit` and state persistence via
//!   `write_to_storage` / `load_group`.

use std::collections::HashMap;
use std::fmt::Debug;
use std::path::{Path, PathBuf};
use std::process::ExitCode;
use std::sync::{Arc, Mutex};

use mls_rs::identity::basic::{BasicCredential, BasicIdentityProvider};
use mls_rs::mls_rules::{CommitOptions, DefaultMlsRules};
use mls_rs::{CipherSuiteProvider, ExtensionList, MlsMessage};
use mls_rs_core::crypto::CryptoProvider;
use mls_rs_core::error::IntoAnyError;
use mls_rs_crypto_rustcrypto::RustCryptoProvider;
use mls_rs_uniffi::config::group_state::{EpochRecord, GroupStateStorage};
use mls_rs_uniffi::{
    generate_signature_keypair, CipherSuite, Client, ClientConfig, CommitEffect, Message,
    ReceivedMessage, SignatureKeypair, SignaturePublicKey, SignatureSecretKey, SigningIdentity,
};
use zeroize::Zeroizing;

/// The directory containing the X.509 test PKI. Defaults to the
/// certificate chains that ship with `mls-rs-crypto-rustcrypto` plus
/// chains generated by `scripts/gen_test_pki.sh`.
fn pki_dir() -> std::path::PathBuf {
    std::env::var("MLS_TEST_PKI_DIR")
        .map(Into::into)
        .unwrap_or_else(|_| {
            std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("../../platform_testbeds/test_pki")
        })
}

/// Simple in-memory [`GroupStateStorage`] used to verify that group
/// state persistence callbacks fire correctly.
#[derive(Debug, Default)]
struct TestStorage {
    state: Mutex<HashMap<Vec<u8>, Vec<u8>>>,
    epochs: Mutex<HashMap<(Vec<u8>, u64), Vec<u8>>>,
}

impl GroupStateStorage for TestStorage {
    fn state(&self, group_id: Vec<u8>) -> Result<Option<Vec<u8>>, mls_rs_uniffi::Error> {
        Ok(self.state.lock().unwrap().get(&group_id).cloned())
    }

    fn epoch(
        &self,
        group_id: Vec<u8>,
        epoch_id: u64,
    ) -> Result<Option<Vec<u8>>, mls_rs_uniffi::Error> {
        Ok(self
            .epochs
            .lock()
            .unwrap()
            .get(&(group_id, epoch_id))
            .cloned())
    }

    fn write(
        &self,
        group_id: Vec<u8>,
        group_state: Vec<u8>,
        epoch_inserts: Vec<EpochRecord>,
        _epoch_updates: Vec<EpochRecord>,
    ) -> Result<(), mls_rs_uniffi::Error> {
        self.state
            .lock()
            .unwrap()
            .insert(group_id.clone(), group_state);
        let mut epochs = self.epochs.lock().unwrap();
        for epoch in epoch_inserts {
            epochs.insert((group_id.clone(), epoch.id), epoch.data);
        }
        Ok(())
    }

    fn max_epoch_id(&self, group_id: Vec<u8>) -> Result<Option<u64>, mls_rs_uniffi::Error> {
        Ok(self
            .epochs
            .lock()
            .unwrap()
            .keys()
            .filter(|(id, _)| *id == group_id)
            .map(|(_, epoch)| *epoch)
            .max())
    }
}

fn all_suites() -> [CipherSuite; 5] {
    [
        CipherSuite::Curve25519Aes128,
        CipherSuite::P256Aes128,
        CipherSuite::Curve25519ChaCha,
        CipherSuite::P521Aes256,
        CipherSuite::P384Aes256,
    ]
}

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

/// File-backed [`mls_rs_core::group::GroupStateStorage`] for the
/// direct-`mls-rs` differential producer. Each `consumer_msg_*` file is
/// verified by a separate `--verify` process, so the producer's group
/// state has to outlive the `--make-welcome` process.
///
/// Layout under `dir`: `<hex(group_id)>.state` plus
/// `<hex(group_id)>.<epoch>.epoch` files. Nothing is deleted —
/// retention is not needed by `load_group`, which only reads the
/// epochs referenced by the current snapshot.
#[derive(Clone, Debug)]
struct FileGroupStateStorage {
    dir: PathBuf,
}

impl FileGroupStateStorage {
    fn new(dir: &Path) -> Self {
        let dir = dir.to_path_buf();
        std::fs::create_dir_all(&dir).expect("create rust_state dir");
        Self { dir }
    }

    fn path(&self, group_id: &[u8], epoch_id: Option<u64>) -> PathBuf {
        match epoch_id {
            Some(id) => self.dir.join(format!("{}.{id}.epoch", hex(group_id))),
            None => self.dir.join(format!("{}.state", hex(group_id))),
        }
    }
}

#[derive(Debug)]
struct StorageIoError(std::io::Error);

impl IntoAnyError for StorageIoError {}

impl From<std::io::Error> for StorageIoError {
    fn from(value: std::io::Error) -> Self {
        Self(value)
    }
}

#[cfg_attr(not(mls_build_async), maybe_async::must_be_sync)]
#[cfg_attr(mls_build_async, maybe_async::must_be_async)]
impl mls_rs_core::group::GroupStateStorage for FileGroupStateStorage {
    type Error = StorageIoError;

    async fn state(&self, group_id: &[u8]) -> Result<Option<Zeroizing<Vec<u8>>>, Self::Error> {
        match std::fs::read(self.path(group_id, None)) {
            Ok(data) => Ok(Some(data.into())),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(None),
            Err(e) => Err(e.into()),
        }
    }

    async fn epoch(
        &self,
        group_id: &[u8],
        epoch_id: u64,
    ) -> Result<Option<Zeroizing<Vec<u8>>>, Self::Error> {
        match std::fs::read(self.path(group_id, Some(epoch_id))) {
            Ok(data) => Ok(Some(data.into())),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(None),
            Err(e) => Err(e.into()),
        }
    }

    async fn write(
        &mut self,
        state: mls_rs_core::group::GroupState,
        inserts: Vec<mls_rs_core::group::EpochRecord>,
        updates: Vec<mls_rs_core::group::EpochRecord>,
    ) -> Result<(), Self::Error> {
        std::fs::write(self.path(&state.id, None), &*state.data)?;
        for record in inserts.into_iter().chain(updates) {
            std::fs::write(self.path(&state.id, Some(record.id)), &*record.data)?;
        }
        Ok(())
    }

    async fn max_epoch_id(&self, group_id: &[u8]) -> Result<Option<u64>, Self::Error> {
        let prefix = format!("{}.", hex(group_id));
        let mut max = None;
        for entry in std::fs::read_dir(&self.dir)? {
            let name = entry?.file_name().to_string_lossy().into_owned();
            if let Some(rest) = name
                .strip_prefix(&prefix)
                .and_then(|s| s.strip_suffix(".epoch"))
            {
                if let Ok(id) = rest.parse::<u64>() {
                    max = Some(max.map_or(id, |m: u64| m.max(id)));
                }
            }
        }
        Ok(max)
    }
}

type DirectClient = mls_rs::Client<
    mls_rs::client_builder::WithIdentityProvider<
        BasicIdentityProvider,
        mls_rs::client_builder::WithCryptoProvider<
            RustCryptoProvider,
            mls_rs::client_builder::WithGroupStateStorage<
                FileGroupStateStorage,
                mls_rs::client_builder::WithMlsRules<
                    DefaultMlsRules,
                    mls_rs::client_builder::BaseConfig,
                >,
            >,
        >,
    >,
>;

/// A `mls_rs::Client` using the RustCrypto provider directly — the
/// ground truth the UniFFI/WASM bindings are compared against.
fn direct_client(id: &[u8], suite: CipherSuite, state_dir: &Path) -> DirectClient {
    let crypto_provider = RustCryptoProvider::default();
    let cs: mls_rs_core::crypto::CipherSuite = suite.into();
    let (secret_key, public_key) = crypto_provider
        .cipher_suite_provider(cs)
        .expect("supported cipher suite")
        .signature_key_generate()
        .expect("signature keypair");
    let credential = BasicCredential::new(id.to_vec()).into_credential();
    let signing_identity = mls_rs::identity::SigningIdentity::new(credential, public_key);
    let commit_options = CommitOptions::default()
        .with_ratchet_tree_extension(true)
        .with_single_welcome_message(true);
    let mls_rules = DefaultMlsRules::new().with_commit_options(commit_options);

    mls_rs::Client::builder()
        .crypto_provider(crypto_provider)
        .identity_provider(BasicIdentityProvider::new())
        .signing_identity(signing_identity, secret_key, cs)
        .group_state_storage(FileGroupStateStorage::new(state_dir))
        .mls_rules(mls_rules)
        .build()
}

/// Full two-party group scenario between `alice` and `bob`.
fn group_scenario(alice: &Client, bob: &Client, label: &str) -> Result<(), mls_rs_uniffi::Error> {
    let alice_group = alice.create_group(None)?;
    let bob_key_package = bob.generate_key_package_message()?;

    let commit = alice_group.add_members(vec![Arc::new(bob_key_package)])?;
    alice_group.process_incoming_message(commit.commit_message.clone())?;
    let bob_group = bob
        .join_group(
            commit.ratchet_tree.clone(),
            &commit.welcome_message.unwrap(),
        )?
        .group;

    let encrypted = alice_group.encrypt_application_message(b"hello, bob")?;
    let received = bob_group.process_incoming_message(Arc::new(encrypted))?;
    match received {
        ReceivedMessage::ApplicationMessage { data, .. } => {
            assert_eq!(data, b"hello, bob", "{label}: plaintext mismatch");
        }
        other => panic!("{label}: expected application message, got {other:?}"),
    }

    // Bob -> Alice round-trip plus a commit from Bob.
    let encrypted = bob_group.encrypt_application_message(b"hello, alice")?;
    let received = alice_group.process_incoming_message(Arc::new(encrypted))?;
    match received {
        ReceivedMessage::ApplicationMessage { data, .. } => {
            assert_eq!(data, b"hello, alice", "{label}: plaintext mismatch");
        }
        other => panic!("{label}: expected application message, got {other:?}"),
    }

    let commit = bob_group.commit()?;
    let received = alice_group.process_incoming_message(commit.commit_message.clone())?;
    assert!(
        matches!(received, ReceivedMessage::Commit { .. }),
        "{label}: expected commit effect"
    );
    // Bob applies his own commit via process on the committer side is
    // already done inside commit(); verify Alice saw a NewEpoch.
    if let ReceivedMessage::Commit { effect, .. } = received {
        assert!(
            matches!(effect, CommitEffect::NewEpoch { .. }),
            "{label}: expected NewEpoch"
        );
    }

    alice_group.write_to_storage()?;
    bob_group.write_to_storage()?;
    Ok(())
}

/// Run the scenario for a given cipher suite using basic credentials.
fn run_suite(suite: CipherSuite) -> Result<(), mls_rs_uniffi::Error> {
    let alice_keypair = generate_signature_keypair(suite)?;
    let alice = Client::new(b"alice".to_vec(), alice_keypair, ClientConfig::default())?;

    let bob_keypair = generate_signature_keypair(suite)?;
    let bob = Client::new(b"bob".to_vec(), bob_keypair, ClientConfig::default())?;

    group_scenario(&alice, &bob, &format!("{suite:?}"))
}

/// Run the scenario where the storage callbacks record state and the
/// group is reloaded from storage afterwards.
fn run_persistence(suite: CipherSuite) -> Result<(), mls_rs_uniffi::Error> {
    let storage = Arc::new(TestStorage::default());
    let config = ClientConfig {
        group_state_storage: storage.clone(),
        ..Default::default()
    };

    let keypair = generate_signature_keypair(suite)?;
    let alice = Client::new(b"alice".to_vec(), keypair, config)?;
    let group = alice.create_group(Some(b"persist-group".to_vec()))?;
    group.write_to_storage()?;

    assert!(
        storage
            .state
            .lock()
            .unwrap()
            .contains_key(b"persist-group".as_slice()),
        "group state was not written to storage"
    );

    let _loaded = alice.load_group(b"persist-group".to_vec())?;
    Ok(())
}

/// Interop surface: message wire-format round trips, roster listing,
/// member removal via a signing identity reconstructed out of band
/// (the cross-language API guarantees these work identically).
fn run_interop(suite: CipherSuite) -> Result<(), mls_rs_uniffi::Error> {
    let alice_keypair = generate_signature_keypair(suite)?;
    let alice = Client::new(b"alice".to_vec(), alice_keypair, ClientConfig::default())?;
    let bob_keypair = generate_signature_keypair(suite)?;
    let bob = Client::new(
        b"bob".to_vec(),
        bob_keypair.clone(),
        ClientConfig::default(),
    )?;

    // Key package over the wire: to_bytes -> Message::from_bytes.
    let kp_bytes = bob.generate_key_package_message()?.to_bytes()?;
    let key_package = Message::from_bytes(&kp_bytes)?;

    let group = alice.create_group(None)?;
    let commit = group.add_members(vec![Arc::new(key_package)])?;
    let welcome_bytes = commit.welcome_message.unwrap().to_bytes()?;
    group.process_incoming_message(commit.commit_message)?;

    let bob_group = bob
        .join_group(None, &Message::from_bytes(&welcome_bytes)?)?
        .group;

    // Roster: both members resolve to application-level identifiers.
    let mut ids: Vec<Vec<u8>> = Vec::new();
    for member in group.members()? {
        ids.push(member.identifier()?);
    }
    ids.sort();
    assert_eq!(ids, [b"alice".to_vec(), b"bob".to_vec()]);

    // Removal by an identity reconstructed without any prior message.
    let bob_identity = SigningIdentity::new_basic(b"bob".to_vec(), bob_keypair.public_key);
    let removal = group.remove_members(&[Arc::new(bob_identity)])?;
    group.process_incoming_message(removal.commit_message.clone())?;
    let received = bob_group.process_incoming_message(removal.commit_message)?;
    assert!(
        matches!(
            received,
            ReceivedMessage::Commit {
                effect: CommitEffect::Removed,
                ..
            }
        ),
        "expected Removed commit effect, got {received:?}"
    );

    // member_with_identity lookup by identifier.
    let alice_id = group.member_with_identity(b"alice".to_vec())?;
    assert_eq!(alice_id.identifier()?, b"alice".to_vec());
    Ok(())
}

fn suite_from_name(name: &str) -> Option<CipherSuite> {
    match name.trim() {
        "Curve25519Aes128" => Some(CipherSuite::Curve25519Aes128),
        "P256Aes128" => Some(CipherSuite::P256Aes128),
        "Curve25519ChaCha" => Some(CipherSuite::Curve25519ChaCha),
        "P521Aes256" => Some(CipherSuite::P521Aes256),
        "P384Aes256" => Some(CipherSuite::P384Aes256),
        _ => None,
    }
}

/// Cross-language wire-interop producer step.
///
/// Reads every `consumer_kp_*.bin` key package written by a
/// Kotlin/Swift/WASM client, validates and commits them all into a
/// fresh group, then writes `welcome.bin`, `commit.bin`, `app_msg.bin`
/// (and `ratchet_tree.bin` when the group emits one) as raw MLS wire
/// bytes. Each consumer then joins the group and decrypts the
/// application message — proving Rust consumed the consumer's bytes
/// and the consumer can consume Rust's.
fn roster_identities<C: mls_rs::client_builder::MlsConfig>(
    group: &mls_rs::Group<C>,
) -> Vec<Vec<u8>> {
    group
        .roster()
        .members()
        .iter()
        .filter_map(|m| m.signing_identity.credential.as_basic())
        .map(|b| b.identifier.to_vec())
        .collect()
}

/// Differential producer step — built on **direct** `mls-rs` (not the
/// UniFFI wrapper) so the emitted fixtures are ground truth for "same
/// inputs -> same outputs" checks on every binding:
///
/// * consumes every `consumer_kp_*.bin` (proving each binding's key
///   package parses and signature-validates under plain `mls-rs`),
/// * emits the group wire bytes (`welcome/commit/app_msg`), plus the
///   golden values a conforming binding must reproduce byte-for-byte:
///   `expected_tree_join.bin` (post-join `export_tree`), a second
///   commit `commit2.bin` with `expected_tree_final.bin`, `app_msg2`,
///   and `expected_roster.txt`.
/// * persists its group state under `rust_state/` so a later
///   `--verify` invocation can decrypt `consumer_msg_*.bin` files.
fn make_welcome(dir: &Path, suite: CipherSuite) -> Result<(), mls_rs_uniffi::Error> {
    let mut key_packages = Vec::new();
    for entry in std::fs::read_dir(dir).expect("read fixture dir") {
        let entry = entry.expect("dir entry");
        let name = entry.file_name().to_string_lossy().into_owned();
        if name.starts_with("consumer_msg") && name.ends_with(".bin") {
            std::fs::remove_file(entry.path()).expect("remove stale consumer message");
        } else if name.starts_with("consumer_kp") && name.ends_with(".bin") {
            let bytes = std::fs::read(entry.path()).expect("read consumer key package");
            key_packages.push((name, bytes));
        }
    }
    assert!(
        !key_packages.is_empty(),
        "no consumer_kp_*.bin fixtures found in {dir:?}"
    );

    // Fresh producer state for this run.
    let state_dir = dir.join("rust_state");
    if state_dir.exists() {
        std::fs::remove_dir_all(&state_dir).expect("reset rust_state");
    }
    let alice = direct_client(b"alice", suite, &state_dir);
    let mut group = alice.create_group_with_id(
        b"interop-group".to_vec(),
        ExtensionList::default(),
        ExtensionList::default(),
        None,
    )?;

    let mut builder = group.commit_builder();
    for (name, bytes) in &key_packages {
        let kp = MlsMessage::from_bytes(bytes)
            .unwrap_or_else(|e| panic!("{name}: not a valid MLS message: {e:?}"));
        builder = builder
            .add_member(kp)
            .unwrap_or_else(|e| panic!("{name}: add_member failed: {e:?}"));
        println!("  {name}: parsed and signature-validated by direct mls-rs");
    }
    let commit = builder.build()?;
    group.apply_pending_commit()?;
    group.write_to_storage()?;

    let write =
        |name: &str, data: &[u8]| std::fs::write(dir.join(name), data).expect("write fixture");
    write("suite.txt", format!("{suite:?}").as_bytes());
    write("alice_id.bin", b"alice");
    write(
        "welcome.bin",
        &commit.welcome_messages.first().unwrap().to_bytes()?,
    );
    if let Some(ratchet_tree) = &commit.ratchet_tree {
        write("ratchet_tree.bin", &ratchet_tree.to_bytes()?);
    }
    write("commit.bin", &commit.commit_message.to_bytes()?);
    let app_msg = group.encrypt_application_message(b"hello from rust", Vec::new())?;
    write("app_msg.bin", &app_msg.to_bytes()?);
    write("plaintext.bin", b"hello from rust");
    write("expected_tree_join.bin", &group.export_tree().to_bytes()?);

    // Second epoch: a carol add produced entirely inside direct
    // mls-rs. Consumers process commit2 and must reach the identical
    // tree — the strongest same-input/same-output check available
    // across the FFI boundary.
    let carol = direct_client(b"carol", suite, &state_dir);
    let carol_kp = carol.generate_key_package_message(
        ExtensionList::default(),
        ExtensionList::default(),
        None,
    )?;
    let commit2 = group.commit_builder().add_member(carol_kp)?.build()?;
    group.apply_pending_commit()?;
    group.write_to_storage()?;
    write("commit2.bin", &commit2.commit_message.to_bytes()?);
    let app_msg2 = group.encrypt_application_message(b"hello from rust epoch2", Vec::new())?;
    write("app_msg2.bin", &app_msg2.to_bytes()?);
    write("plaintext2.bin", b"hello from rust epoch2");
    write("expected_tree_final.bin", &group.export_tree().to_bytes()?);

    let mut roster = roster_identities(&group);
    roster.sort();
    let roster_text: Vec<String> = roster
        .iter()
        .map(|id| String::from_utf8_lossy(id).into_owned())
        .collect();
    write("expected_roster.txt", roster_text.join("\n").as_bytes());
    Ok(())
}

/// Differential consumer step for the reverse direction: load the
/// producer's group (persisted by `--make-welcome`) and decrypt every
/// `consumer_msg_*.bin` the bindings emitted, checking the plaintext.
/// Proves a binding's encrypted output is consumed identically by the
/// direct Rust library.
fn verify_consumer_msgs(dir: &Path, suite: CipherSuite) -> Result<(), mls_rs_uniffi::Error> {
    let state_dir = dir.join("rust_state");
    let alice = direct_client(b"alice", suite, &state_dir);
    let mut group = alice.load_group(b"interop-group")?;

    let mut found = false;
    for entry in std::fs::read_dir(dir).expect("read fixture dir") {
        let entry = entry.expect("dir entry");
        let name = entry.file_name().to_string_lossy().into_owned();
        if !(name.starts_with("consumer_msg") && name.ends_with(".bin")) {
            continue;
        }
        found = true;
        let lang = name
            .trim_start_matches("consumer_msg_")
            .trim_end_matches(".bin");
        let bytes = std::fs::read(entry.path()).expect("read consumer message");
        let msg = MlsMessage::from_bytes(&bytes)
            .unwrap_or_else(|e| panic!("{name}: not a valid MLS message: {e:?}"));
        let description = group
            .process_incoming_message(msg)
            .unwrap_or_else(|e| panic!("{name}: process failed: {e:?}"));
        match description {
            mls_rs::group::ReceivedMessage::ApplicationMessage(desc) => {
                let expected = format!("hello from {lang}").into_bytes();
                assert_eq!(desc.data(), &expected, "{name}: plaintext mismatch");
                println!("  {name}: decrypted by direct mls-rs");
            }
            other => panic!("{name}: expected application message, got {other:?}"),
        }
    }
    if !found {
        println!("  no consumer_msg_*.bin to verify");
    }
    Ok(())
}

/// A PEM private key + DER certificate chain describing one X.509
/// identity.
struct X509Identity {
    certificate_chain: Vec<Vec<u8>>,
    suite: CipherSuite,
    public_key: Vec<u8>,
    secret_key: Vec<u8>,
}

fn load_der(path: &std::path::Path) -> Vec<u8> {
    std::fs::read(path).unwrap_or_else(|e| panic!("reading {}: {e}", path.display()))
}

fn load_pem(path: &std::path::Path) -> String {
    std::fs::read_to_string(path).unwrap_or_else(|e| panic!("reading {}: {e}", path.display()))
}

/// Load an identity generated by `scripts/gen_test_pki.sh`:
/// `test_pki/<name>/{cert.der,key.pem}` where `<name>` is
/// `<curve>_alice` or `<curve>_bob`.
fn pki_identity(name: &str, suite: CipherSuite) -> X509Identity {
    let dir = pki_dir().join(name);
    let key_pem = load_pem(&dir.join("key.pem"));
    let chain = vec![load_der(&dir.join("cert.der"))];

    let (public_key, secret_key) = match suite {
        CipherSuite::Curve25519Aes128 | CipherSuite::Curve25519ChaCha => {
            use ed25519_dalek::pkcs8::DecodePrivateKey;

            let key = ed25519_dalek::SigningKey::from_pkcs8_pem(&key_pem).expect("Ed25519 key");
            (
                key.verifying_key().to_bytes().to_vec(),
                // The provider stores Ed25519 secret keys as the
                // 64-byte keypair encoding.
                key.to_keypair_bytes().to_vec(),
            )
        }
        CipherSuite::P256Aes128 => {
            use p256::{elliptic_curve::sec1::ToEncodedPoint, pkcs8::DecodePrivateKey};

            let key = p256::SecretKey::from_pkcs8_pem(&key_pem).expect("P-256 key");
            (
                key.public_key().to_encoded_point(false).as_bytes().to_vec(),
                key.to_bytes().to_vec(),
            )
        }
        CipherSuite::P384Aes256 => {
            use p384::{elliptic_curve::sec1::ToEncodedPoint, pkcs8::DecodePrivateKey};

            let key = p384::SecretKey::from_pkcs8_pem(&key_pem).expect("P-384 key");
            (
                key.public_key().to_encoded_point(false).as_bytes().to_vec(),
                key.to_bytes().to_vec(),
            )
        }
        CipherSuite::P521Aes256 => {
            use p521::{elliptic_curve::sec1::ToEncodedPoint, pkcs8::DecodePrivateKey};

            let key = p521::SecretKey::from_pkcs8_pem(&key_pem).expect("P-521 key");
            (
                key.public_key().to_encoded_point(false).as_bytes().to_vec(),
                key.to_bytes().to_vec(),
            )
        }
    };

    X509Identity {
        certificate_chain: chain,
        suite,
        public_key,
        secret_key,
    }
}

fn keypair_of(identity: &X509Identity) -> SignatureKeypair {
    SignatureKeypair {
        cipher_suite: identity.suite,
        public_key: SignaturePublicKey {
            bytes: identity.public_key.clone(),
        },
        secret_key: SignatureSecretKey {
            bytes: identity.secret_key.clone(),
        },
    }
}

/// End-to-end X.509 scenario: both clients authenticate with
/// certificate chains that anchor at `trust_root` (or are self-signed
/// when `self_signed` is set).
fn run_x509(
    alice_id: X509Identity,
    bob_id: X509Identity,
    trust_root: Option<Vec<u8>>,
    self_signed: bool,
    label: &str,
) -> Result<(), mls_rs_uniffi::Error> {
    let config = ClientConfig {
        root_ca_certificates: trust_root.into_iter().collect(),
        allow_self_signed_certificates: self_signed,
        ..Default::default()
    };

    let alice = Client::new_with_x509(
        alice_id.certificate_chain.clone(),
        keypair_of(&alice_id),
        config.clone(),
    )?;
    let bob = Client::new_with_x509(
        bob_id.certificate_chain.clone(),
        keypair_of(&bob_id),
        config,
    )?;

    group_scenario(&alice, &bob, label)
}

fn main() -> ExitCode {
    let args: Vec<String> = std::env::args().collect();
    if args.len() == 4 && args[1] == "--make-welcome" {
        let dir = std::path::PathBuf::from(&args[2]);
        let suite = suite_from_name(&args[3]).expect("unknown cipher suite name");
        return match make_welcome(&dir, suite) {
            Ok(()) => {
                println!("wrote welcome/commit/app_msg fixtures to {}", dir.display());
                ExitCode::SUCCESS
            }
            Err(err) => {
                eprintln!("make-welcome failed: {err:?}");
                ExitCode::FAILURE
            }
        };
    }

    if args.len() == 4 && args[1] == "--verify" {
        let dir = std::path::PathBuf::from(&args[2]);
        let suite = suite_from_name(&args[3]).expect("unknown cipher suite name");
        return match verify_consumer_msgs(&dir, suite) {
            Ok(()) => ExitCode::SUCCESS,
            Err(err) => {
                eprintln!("verify failed: {err:?}");
                ExitCode::FAILURE
            }
        };
    }

    let mut failures = 0;

    for suite in all_suites() {
        match run_suite(suite) {
            Ok(()) => println!("PASS basic e2e          {suite:?}"),
            Err(err) => {
                failures += 1;
                eprintln!("FAIL basic e2e          {suite:?}: {err:?}");
            }
        }
    }

    match run_interop(CipherSuite::Curve25519Aes128) {
        Ok(()) => println!("PASS interop surface   Curve25519Aes128"),
        Err(err) => {
            failures += 1;
            eprintln!("FAIL interop surface   Curve25519Aes128: {err:?}");
        }
    }

    match run_persistence(CipherSuite::Curve25519Aes128) {
        Ok(()) => println!("PASS persistence       Curve25519Aes128"),
        Err(err) => {
            failures += 1;
            eprintln!("FAIL persistence       Curve25519Aes128: {err:?}");
        }
    }

    // X.509 end-to-end: each client authenticates with a leaf
    // certificate signed by a per-curve root CA. The chains are
    // generated by scripts/gen_test_pki.sh.
    for (curve, suite) in [
        ("ed25519", CipherSuite::Curve25519Aes128),
        ("ed25519", CipherSuite::Curve25519ChaCha),
        ("p256", CipherSuite::P256Aes128),
        ("p384", CipherSuite::P384Aes256),
        ("p521", CipherSuite::P521Aes256),
    ] {
        let ca_dir = pki_dir().join(format!("{curve}_ca"));
        let alice_dir = pki_dir().join(format!("{curve}_alice"));
        let bob_dir = pki_dir().join(format!("{curve}_bob"));
        let label = format!("x509-{curve}-{suite:?}");

        if !ca_dir.join("cert.der").exists()
            || !alice_dir.join("cert.der").exists()
            || !bob_dir.join("cert.der").exists()
        {
            println!("SKIP {label}: run scripts/gen_test_pki.sh first");
            continue;
        }

        let root_ca = load_der(&ca_dir.join("cert.der"));
        match run_x509(
            pki_identity(&format!("{curve}_alice"), suite),
            pki_identity(&format!("{curve}_bob"), suite),
            Some(root_ca),
            false,
            &label,
        ) {
            Ok(()) => println!("PASS x509 e2e          {label}"),
            Err(err) => {
                failures += 1;
                eprintln!("FAIL x509 e2e          {label}: {err:?}");
            }
        }
    }

    if failures == 0 {
        println!("All end-to-end scenarios passed.");
        ExitCode::SUCCESS
    } else {
        eprintln!("{failures} scenario(s) failed.");
        ExitCode::FAILURE
    }
}
